           // N A D R A--M A N A G E M E N T--S Y S T E M
#include <stdio.h>
unsigned int id_gen(void){
	int id=time(NULL);
	return id;	
}
void main (){
/* Admin ka eik pasword, and full access
user login hoga without pass/id, only view status but with ID/pass only and timmings etc
Back (nt psbl) and Exit? 
Family registerion?*
Status track?
ID generator?
Serach Engine?
Filing??????*
Designing?
Presentation??
*/ 
   
	printf("1.Login as Administrator\n2.Login as User\n");
	int choice_l;
	scanf("%d",&choice_l);
    printf("Select from following:\n1.ID Documents\n2.Timmings\n3.Complaints\n4.About Us\n5.Public Engagemnet\n6.Back\n7.Exit\n");
    int choice_m;
    scanf("%d",&choice_m);
	int choice_d;
	char fname[20],gen[9],dob[15],stay[20];
	char name_g[20],nat_g[15],cnic_g[15],rel_g[14],age_g[3],martials_g[15],fname_g[20],fcnic_g[15],add_g[50],dist_g[20];
	char name_b[20],nat_b[15],cnic_b[15],rel_b[14],age_b[3],martials_b[15],fname_b[20],fcnic_b[15],add_b[50],dist_b[20];
	
	char fathername[30],gender[8],address[30],issuedate[15],country[20],expdate[15],dateofbirth[15],identitynumber[25];
	char relation[20],applicant[20],applicantcnic[20],birthmark[30],district[20],fathercnic[20],fathernationality[20];
	char mothername[20],mothernationality[20],mothercnic[20],grandfathername[25],grandfathercnic[20],registrationnumber[20],disability[20];
	
	char f_name[20];
	int identity_no[20],DOB[15],DOI[15],DOE[15];
	int passport[15],CNIC[19],vac1[10],vac2[10];
	int CRMS[10],FORM[10], cnic[16],DOD[15],DOBU[15],SICK[10],E_D[16],I_D[16];
	char nature[10],name[50],rel[20],house[50],city[20],tehsil[20], deceased[50],d_cnic[16],GRAVEYARD[20],sex[15];
	char religion[20],p_of_death[20],R_O_D[30],A_I[30];
	
	int choice_AS;
	
	char nationality[15],namofcent1[20],vac_nam1[15],namofcent2[20],vac_nam2[15];
	//system("cls");
	switch (choice_m){
		case 1:
			printf("1.Add\n2.View status\n");
			scanf("%d",&choice_AS);
			switch(choice_AS)
			{
			case 1:
	printf("Select from following options:\n1.National Identity Card(NIC)\n2.Smart National Identity Card(SNIC)\n3.Birth certificate\n4.B-form\n5.NIC for Overseas Pakistanis(NICOP)\n6.Marriage Registeration Certificate\n7.Divorce Registeration Certificate\n8.Juvenile Card\n9.Vaccination Card\n10.Death Certificate\n11.Back\n12.Exit\n");
	scanf("%d",&choice_d);
	switch(choice_d)
	    {
		case 1:
			printf("Name: ");
			fflush(stdin);
			gets(name);
			printf("Father's Name: ");
			gets(fathername);
			printf("Gender: ");
			gets(gender);
			printf("Identity number: ");
			gets(identitynumber);
			printf("Date of birth(DD/MM/YYYY): ");
			fflush(stdin);
			gets(dateofbirth);
			printf("Nationality: ");
			gets(country);
			printf("Religion: ");
			gets(religion);
			printf("Permanent Address: ");
			gets(address);
			printf("Date of issue(DD/MM/YYYY): ");
			gets(issuedate);
			printf("Birth Mark: ");
			gets(birthmark);
			printf("\n\n");
		    printf("_____________________________________________\n");
		    printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
		    printf("\t   GOVERNMENT OF PAKISTAN\n\n");
		    printf(" ");
			printf(" ");
			printf(" ");
			printf(" ");
			printf("\tNATIONAL IDENTITY CARD\n");
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("Name: ");puts(name);printf("\n");
			printf("Father's name: ");puts(fathername);printf("\n");
			printf("Gender: ");puts(gender);printf("\n");
			printf("identity number: ");puts(identitynumber);printf("\n");
			printf("Date of birth: ");puts(dateofbirth);printf("\n");
			printf("Nationality: ");puts(country);printf("\n");
			printf("Religion: ");puts(religion);printf("\n");
			printf("Permanent Address: ");puts(address);printf("\n");
			printf("Date of issue: ");puts(dateofbirth);printf("\n");
		    printf("Birth Mark: ");puts(birthmark);
		    printf("\nYour tracking id is : %u\n",id_gen());
		    printf("\n\n");
		    printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
		    
			printf("_____________________________________________\n");
			break;
			
		case 2:
			printf("Name: ");
			fflush(stdin);
			gets(name);
			printf("Father's Name: ");
			gets(fathername);
			printf("Gender: ");
			gets(gender);
			printf("Identity number: ");
			gets(identitynumber);
			printf("Date of birth(DD/MM/YYYY): ");
			fflush(stdin);
			gets(dateofbirth);
			printf("Nationality: ");
			gets(country);
			printf("Religion: ");
			gets(religion);
			printf("Permanent Address: ");
			gets(address);
			printf("Date of issue(DD/MM/YYYY): ");
			gets(issuedate);
			printf("Birth Mark: ");gets(birthmark);
		    printf("_____________________________________________\n");
		    printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
		    printf("\t   GOVERNMENT OF PAKISTAN\n\n");
		    printf("\tSMART NATIONAL IDENTITY CARD\n");
		    printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("Name: ");puts(name);printf("\n");
			printf("Father's name: ");puts(fathername);printf("\n");
			printf("Gender: ");puts(gender);printf("\n");
			printf("identity number: ");puts(identitynumber);printf("\n");
			printf("Date of birth: ");puts(dateofbirth);printf("\n");
			printf("Nationality: ");puts(country);printf("\n");
			printf("Religion: ");puts(religion);printf("\n");
			printf("Permanent Address: ");puts(address);printf("\n");
			printf("Date of issue: ");puts(dateofbirth);printf("\n");
		    printf("Birth Mark: ");puts(birthmark);
		    printf("\nYour tracking id is : %u\n",id_gen());
			printf("\n\n");
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
		    
			printf("_____________________________________________\n");
			break;
			break;
		case 3:
			printf("Name of child: ");
			fflush(stdin);
			gets(name);
			printf("Date of birth: ");
			gets(dateofbirth);
			printf("Gender: ");
			gets(gender);
			printf("District of birth: ");
			gets(district);
			printf("Father's name: ");
			gets(fathername);
			printf("Nationality of father:");
			gets(fathernationality);
			printf("CNIC No. of Father: ");
			gets(fathercnic);
			printf("Mother's name: ");
			gets(mothername);
			printf("Nationality of mother: ");
			gets(mothernationality);
			printf("CNIC No. of mother: ");
			gets(mothercnic);
			printf("Grandfather's name: ");
			gets(grandfathername);
			printf("Grand father's CNIC No. : ");
			gets(grandfathercnic);
			printf("address: ");
			gets(address);
			printf("Name of applicant: ");
			gets(applicant);
			printf("Relation with child: ");
			gets(relation);
			printf("\n\n");
			
			printf("_____________________________________________\n");
			printf("\t   GOVERNMENT OF PAKISTAN\n\n");
			printf("\tBirth Registration Certificate\n");
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("\t\tChild's Detail\n\n");
			printf("Name: ");
			puts(name);
			printf("Date of birth: ");
			puts(dateofbirth);
			printf("Gender: ");
			puts(gender);
			printf("District of birth: ");
			puts(district);
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("  ");printf("     \tParental Information\n\n");
			printf("Father's name: ");
			puts(fathername);
			printf("Nationality of father:");
			puts(fathernationality);
			printf("CNIC No. of Father: ");
			puts(fathercnic);
			printf("Mother's name: ");
			puts(mothername);
			printf("Nationality of mother: ");
			puts(mothernationality);
			printf("CNIC No. of mother: ");
			puts(mothercnic);
			printf("Grandfather's name: ");
			puts(grandfathername);
			printf("Grand father's CNIC No. : ");
			puts(grandfathercnic);
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("   \t\tAddress\n\n");
			printf("address: ");
			puts(address);
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("    \tApplicant's Information\n\n");
			printf("Name of applicant: ");
			puts(applicant);
			printf("Relation with child: ");
			puts(relation);
			printf("\n");
			printf("\nYour tracking id is : %u\n",id_gen());
			printf("_____________________________________________\n");
			break;
		case 4:
			printf("Name of applicant: ");
			fflush(stdin);
			gets(applicant);
			printf("CNIC No. of applicant: ");
			gets(applicantcnic);
			printf("Name of child: ");
			gets(name);
			printf("Gender: ");
			gets(gender);
			printf("Registration number: ");
			gets(registrationnumber);
			printf("Father's name: ");
			gets(fathername);
			printf("CNIC No. of Father: ");
			gets(fathercnic);
			printf("Mother's name: ");
			gets(mothername);
			printf("CNIC No. of mother: ");
			gets(mothercnic);
			
			printf("Date of birth: ");
			gets(dateofbirth);
			printf("Disability: ");
			gets(disability);
			printf("\n\n");
			
			printf("_____________________________________________\n");
			printf("\t   GOVERNMENT OF PAKISTAN\n\n");
			printf("  ");printf("\t\tB-Form\n");
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("Name of applicant: ");
			puts(applicant);
			printf("CNIC No. of applicant: ");
			puts(applicantcnic);
			printf("Name of child: ");
			puts(name);
			printf("Gender: ");
			puts(gender);
			printf("Registration number: ");
			puts(registrationnumber);
			printf("Father's name: ");
			puts(fathername);
			printf("CNIC No. of Father: ");
			puts(fathercnic);
			printf("Mother's name: ");
			puts(mothername);
			printf("CNIC No. of mother: ");
			puts(mothercnic);
			
			printf("Date of birth: ");
			puts(dateofbirth);
			printf("Disability: ");
			puts(disability);
			printf("\nYour tracking id is : %u\n",id_gen());
			printf("\n\n");
			printf("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n");
			printf("_____________________________________________\n");
			
			break;
				case 5:
			printf("Enter the following details:\n1.Name:  ");
			fflush(stdin);	
			gets(name);
			printf("\n2.Father's Name:  ");
			gets(fname);
			printf("\n3.Gender:  ");
			gets(gen);
			printf("\n4.Date of Birth(DD/MM/YYYY):  ");
			gets(dob);
			printf("\n5.Country of Stay:  ");
			gets(stay);
			printf("\n------------------------------------------------------\n------------------------------------------------------\n");
            printf("\t\t   NICOP CARD\n------------------------------------------------------\n------------------------------------------------------\n");
	        printf("   Name: ");
	        puts(name);
	        printf("\n   Father's Name: ");
	        puts(fname);
	        printf("\n   Gender: ");
	        puts(gen);
	        printf("\n   Date of Birth: ");
	        puts(dob);
	        printf("\n   Country of Stay: ");
	        puts(stay);
			printf("\nYour tracking id is : %u\n",id_gen());	             
			break;
        case 6:
       printf("Enter Particulars of Groom:\n1.Name  ");
       fflush(stdin);
       gets(name_g);
       printf("\n2.Nationality:  ");
       gets(nat_g);
       printf("\n3.CNIC.NO:  ");
       gets(cnic_g);
       printf("\n4.Religion:  ");
       gets(rel_g);
       printf("\n5.Age:  ");
       gets(age_g);
       printf("\n6.Martial Status:  ");
       gets(martials_g);
       printf("\n7.Father's Name:  ");
       gets(fname_g);
       printf("\n8.CNIC.NO:  ");
       gets(fcnic_g);
	   printf("\n9.Address:  ");
	   gets(add_g);
	   printf("\n10.District:  ");
	   gets(dist_g);        	
       printf("\n\nEnter Particulars of Bride:\n1.Name  ");
       fflush(stdin);
       gets(name_b);
       printf("\n2.Nationality:  ");
       gets(nat_b);
       printf("\n3.CNIC.NO:  ");
       gets(cnic_b);
       printf("\n4.Religion:  ");
       gets(rel_b);
       printf("\n5.Age:  ");
       gets(age_b);
       printf("\n6.Martial Status:  ");
       gets(martials_b);
       printf("\n7.Father's Name:  ");
       gets(fname_b);
       printf("\n8.CNIC.NO:  ");
       gets(fcnic_b);
	   printf("\n9.Address:  ");
	   gets(add_b);
	   printf("\n10.District:  ");
	   gets(dist_b);
	   	printf("\n------------------------------------------------------\n------------------------------------------------------\n");
    printf("\tMARRIAGE REGISTERATION CERTIFICATE\n------------------------------------------------------\n------------------------------------------------------\n");
	printf("\t     Particulars of Groom\n------------------------------------------------------\n");
	printf("   Name: ");
	puts(name_g);
	printf("\n   Nationality: ");
	puts(nat_g);
	printf("\n   CNIC NO: ");
	puts(cnic_g);
	printf("\n   Religion: ");
	puts(rel_g);
	printf("\n   Age: ");
	puts(age_g);
	printf("\n   Martial Status: ");
	puts(martials_g);
	printf("\n   Father's Name: ");
	puts(fname_g);
	printf("\n   CNIC NO: ");
	puts(fcnic_g);
	printf("\n   Address: ");
	puts(add_g);
	printf("\n   District: ");
	puts(dist_g);
	printf("------------------------------------------------------\n\t     Particulars of Bride\n------------------------------------------------------\n");
	printf("   Name: ");
	puts(name_b);
	printf("\n   Nationality: ");
	puts(nat_b);
	printf("\n   CNIC NO: ");
	puts(cnic_b);
	printf("\n   Religion: ");
	puts(rel_b);
	printf("\n   Age: ");
	puts(age_b);
	printf("\n   Martial Status: ");
	puts(martials_b);
	printf("\n   Father's Name: ");
	puts(fname_b);
	printf("\n   CNIC NO: ");
	puts(fcnic_b);
	printf("\n   Address: ");
	puts(add_b);
	printf("\n   District: ");
	puts(dist_b);
	printf("\nYour tracking id is : %u\n",id_gen());	   
	 break;
        case 7:
       printf("Enter Divorcer's Details:\n1.Name  ");
       fflush(stdin);
       gets(name_g);
       printf("\n2.Nationality:  ");
       gets(nat_g);
       printf("\n3.CNIC.NO:  ");
       gets(cnic_g);
       printf("\n4.Religion:  ");
       gets(rel_g);
       printf("\n5.Age:  ");
       gets(age_g);
       printf("\n6.Father's Name:  ");
       gets(fname_g);
       printf("\n7.CNIC.NO:  ");
       gets(fcnic_g);
	   printf("\n8.Address:  ");
	   gets(add_g);
	   printf("\n9.District:  ");
	   gets(dist_g);        	
       printf("\n\nEnter Divorcee's Details:\n1.Name  ");
       fflush(stdin);
       gets(name_b);
       printf("\n2.Nationality:  ");
       gets(nat_b);
       printf("\n3.CNIC.NO:  ");
       gets(cnic_b);
       printf("\n4.Religion:  ");
       gets(rel_b);
       printf("\n5.Age:  ");
       gets(age_b);
       printf("\n6.Father's Name:  ");
       gets(fname_b);
       printf("\n7.CNIC.NO:  ");
       gets(fcnic_b);
	   printf("\n8.Address:  ");
	   gets(add_b);
	   printf("\n9.District:  ");
	   gets(dist_b);
	   	printf("\n------------------------------------------------------\n------------------------------------------------------\n");
    	printf("\tDivorce REGISTERATION CERTIFICATE\n------------------------------------------------------\n------------------------------------------------------\n");
		printf("\t     Divorcer's Details\n------------------------------------------------------\n");
	 	printf("   Name: ");
		puts(name_g);
		printf("\n   Nationality: ");
		puts(nat_g);
		printf("\n   CNIC NO: ");
		puts(cnic_g);
		printf("\n   Religion: ");
	puts(rel_g);
	printf("\n   Age: ");
	puts(age_g);
	printf("\n   Father's Name: ");
	puts(fname_g);
	printf("\n   CNIC NO: ");
	puts(fcnic_g);
	printf("\n   Address: ");
	puts(add_g);
	printf("\n   District: ");
	puts(dist_g);
	printf("------------------------------------------------------\n\t    Divorcee's Details\n------------------------------------------------------\n");
	printf("   Name: ");
	puts(name_b);
	printf("\n   Nationality: ");
	puts(nat_b);
	printf("\n   CNIC NO: ");
	puts(cnic_b);
	printf("\n   Religion: ");
	puts(rel_b);
	printf("\n   Age: ");
	puts(age_b);
	printf("\n   Father's Name: ");
	puts(fname_b);
	printf("\n   CNIC NO: ");
	puts(fcnic_b);
	printf("\n   Address: ");
	puts(add_b);
	printf("\n   District: ");
	puts(dist_b);	   
	 break;	 
	 case 8:
	 printf("Name: ");
	 fflush(stdin);
	gets(name);
	printf("Father Name: ");
	gets(f_name);
	printf("Gender: ");
	gets(gender);
	printf("Country Of Stay: ");
	gets(country);
	printf("Identity Number: ");
	gets(identity_no);
	printf("Date Of Birth: ");
	gets(DOB);
	printf("Date Of Insurace: ");
	gets(DOI);
	printf("Date Of Expiry: ");
	gets(DOE);	
	printf("____________________________________________________________________\n");
	printf("\t\t\t\t\t\t   Only For UNDER 18");
	printf("\n\nPAKISTAN\t\t\tNational Identity Card");
	printf("\n-----------\nISLAMIC REPUBLIC OF PAKISTAN");
	printf("Name: ");
	puts(name);
	printf("Father Name: ");
	puts(f_name);
	printf("Gender: ");
	puts(gender);
	printf("Country Of Stay: ");
	puts(country);
	printf("Country Of Stay: ");
	puts(identity_no);
	printf("Date Of Birth: ");	
	puts(DOB);
	printf("Date Of Insurace: ");
	puts(DOI);
	printf("Date Of Expiry: ");	
	puts(DOE);
	printf("\nYour tracking id is : %u\n",id_gen());
	break;
	case 9:
		printf("IMMUNIZATION CERTIFICATE FOR COVID-19\n");	
		printf("ENTER NAME: ");
		gets(name);
		printf("ENTER THE DATE OF BIRTH[DD-MM-YY]: ");
		gets(DOB);
		printf("ENTER THE NATIONALITY: ");	
		gets(nationality);
		printf("ENTER THE CNIC NO.: ");
		gets(CNIC);
		printf("ENTER THE PASSPORT NO.: ");
		gets(passport);	
		printf("\nhas been administered following COVID-19 vaccination\n");
	
		printf("ENTER DATE OF 1 VACCINATION DOSE[DD-MM-YY]: ");
		gets(vac1);
		printf("ENTER THE NAME OF CENTRE: ");
		gets(namofcent1);
		printf("ENTER THE VACCINE MANUFACTURER NAME: ");
		gets(vac_nam1);	
		printf("ENTER DATE OF 2 VACCINATION DOSE[DD-MM-YY]: ");
		gets(vac2);
		printf("ENTER THE NAME OF CENTRE: ");
		gets(namofcent2);
		printf("ENTER THE VACCINE MANUFACTURER NAME: ");
		gets(vac_nam2);	
	
		printf("\n---------------------------------------------------------\n");
		printf("Name: ");
		puts(name);
		printf("CNIC NO.:");
		puts(CNIC);
		printf("Date Of Birth: ");
		puts(DOB);
		printf("Nationality: ");
		puts(nationality);
	    printf("Passport No.: ");
		puts(passport);
		printf("Vaccine\t   Date\t    Name of Health Centre\tVaccine Manufacturer Name\n");
		printf("1\t %s\t   %s\t\t\t%s", vac1 , namofcent1 , vac_nam1);
	    printf("\n");
		printf("2\t %s\t   %s\t\t\t%s", vac2 , namofcent2 , vac_nam2);  
		break;
		case 10:
	printf("CRMS NO: ");
	fflush(stdin);
	gets(CRMS);
	printf("FORM NO: ");
	gets(FORM);
	printf("NATURE OF DEATH: ");
	gets(nature);
	printf("APPLICANT NAME: ");
	gets(name);
	printf("APPLICANT CNIC: ");
	gets(cnic);
	printf("RELATION WITH DECEASED: ");
	gets(rel);
	printf("ADDRESS: HOUSE#: ");
	gets(house);
	printf("CITY: ");
	gets(city);
	printf("TEHSIL: ");
	gets(tehsil);
	printf("DISTRICT: ");
	gets(district);
	printf("DECEASED NAME: ");
	fflush(stdin);
	gets(deceased);
	printf("DECEASED CNIC: ");
	gets(d_cnic);
	printf("FATHER NAME: ");
	gets(f_name);
	printf("DATE OF BIRTH: ");
	gets(DOB);
	printf("SEX: ");
	gets(sex);
	printf("RELIGION: ");
	gets(religion);
	printf("PLACE OF DEATH: ");
	gets(p_of_death);
	printf("DATE OF DEATH: ");
	gets(DOD);
	printf("DATE OF BURIAL: ");
	gets(DOBU);
	printf("GRAVEYARD NAME: ");
	gets(GRAVEYARD);
	printf("ENTRY DATE:  ");
	gets(E_D);
	printf("ISSUE DATE: ");
	gets(I_D);
	printf("ADDITIONAL INFORMATION: ");
	gets(A_I);
	
	//---------------------------------------------------------------------------------------------------------
	//for output
	
	printf("\t\tTHE GOVT. OF SINDH PAKISTAN\n\n\t\t    DEATH CERTIFICTE\n\n");
	printf("CRMS NO: %s\t\t\t\t\tFORM NO: %s\n",CRMS ,FORM );
	printf("NATURE OF DEATH: ");
	puts(nature);
	printf("APPLICANT NAME: ");	
	puts(name);
	printf("CNIC: %s\t\tRELATION WITH DECEASED: %s\n", cnic, rel);
	printf("ADDRESS: HOUSE#: ");
	puts(house);
	printf("CITY: %s\tTEHSIL: %s\tDISTRICT: %s\n\n",city, tehsil,district);
	printf("DECEASED NAME:%s\nFATHER NAME: %s\nDATE OF BIRTH:%s\nSEX: %s\nRELIGION: %s\nPLACE: %s\nDATE OF BURIAL: %s",deceased, f_name, DOB, sex,religion,p_of_death, DOBU  );
	printf("NAME: %s\nCNIC: %s\nGRAVEYARD NAME: %s\nENTRY DATE: %s\nISSUE DATE: %s\nADDITIONAL INFO: %s", deceased, d_cnic, GRAVEYARD, E_D, I_D,A_I);
    printf("\nYour tracking id is : %u\n",id_gen());
	break;
	    }
	    break;
	    case 2:
	    	printf("Miss say Pochna hai !\n");
	    	break;
    }
	break;
		case 2:
			printf("To be added\n");
	break;
		case 3:
			printf("TO be added\n");
		break;
		case 4:
			printf("To be added\n");
		break;
		case 5:
			printf("TO be added\n");
	break;
		case 6:
			printf("Miss say Pochna hai !\n");		
		break;
		case 7:
			printf("Miss say Pochna hai !\n");	
	break;
}
}
